#### Capstone Project EDA

In this script, we perform basic EDA on each of the provided datasets to determine their size, features, and potential relevance for future analysis

Datasets include: appearances, club games, clubs, competitions, games, game events, game linueps, player valuations, players, and transfers

In [2]:
import pandas as pd

#Load and examine transfer data set
transfers = pd.read_csv("data/transfers.csv")
transfers.head()

#Dimensions of the data
transfers.shape

#Look at missing values
transfers.isna().sum()

#Summary stats for numeric columns
transfers.describe()

#Look at observation with the highest transfer fee
transfers[transfers['transfer_fee'] == 180000000.0]

#Look at observation with the highest market value
transfers[transfers['market_value_in_eur'] == 180000000.0]

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
14998,342229,2024-07-01,24/25,583,418,PSG,Real Madrid,0.0,180000000.0,Kylian Mbappé

Dim: (99557, 10)
- 12589 unique players 

Relevant fields: player_id, transfer_date, transfer_season, from_club_name, to_club_name, transfer_fee, market_value_in_eur, and player_name. 

Many NA values in transfer_fee and market_value_in_eur
- Transfer fees may be undisclosed? Or just poor data quality 

transfer_fee and market_value_in_eur column are both heavily right skewed
- Not surprising for financial data 

TBD if transfer data will be relevant for analysis- many missing values

In [ ]:
#Load and examine players data set
players = pd.read_csv("data/players.csv")
players.head()

#Dimensions of the data
players.shape
players.columns

#Look at missing values
players.isna().sum()

#Summary stats for numeric columns
players.describe()

#Look at observation with the highest highest market value
players[players['highest_market_value_in_eur'] == 200000000.0]

Index(['player_id', 'first_name', 'last_name', 'name', 'last_season',
       'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth',
       'country_of_citizenship', 'date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name',
       'image_url', 'url', 'current_club_domestic_competition_id',
       'current_club_name', 'market_value_in_eur',
       'highest_market_value_in_eur'],
      dtype='object')

Dim: (34309, 23)
- One record for each player

Relevant fields: player_id, name, last_season, position, sub_position, contract_expiration_date, current_club_name, market_value_in_eur, highest_market_value_in_eur

Some NA values in sub_position, contract_expiration_date, market_value_in_eur, and highest_market_value_in_eur

market_value_in_eur and highest_market_value_in_eur column are both right skewed
- Highest market value may be different than current value; Look into how many players are at their "best" right now

In [3]:
#Load and examine player valuations data set 
#Contains historical market values for players
valuations = pd.read_csv("data/player_valuations.csv")
valuations.head()

#Dimensions of the data
valuations.shape

#Look at missing values
valuations.isna().sum()

#Summary stats for numeric columns
valuations.describe()

valuations[valuations['market_value_in_eur'] == 0.0]

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
15123,60096,2008-03-17,0,NK Maribor,2696,RU1

Dim: (435375, 6)
- 31987 unique players

Relevant fields: player_id, date, market_value_in_eur

Dates range from 2000-01-20 to 2026-02-28
- Assume that different players will have different number of records depending on how many seasons they played and completeness of data
- Consider filtering this range if it will improve data quality

In [ ]:
#Load and examine games data set 
games = pd.read_csv("data/games.csv")
games.head()

#Dimensions of the data
games.shape
games.columns

Dim:(78114, 23)

Will likely not be relevant for the analysis- contains information about games played (teams, location, score, etc.) but nothing about individual players

In [10]:
#Load and examine lineups data
lineups = pd.read_csv("data/game_lineups.csv")
lineups.head()

#Dimensions of the data
#lineups.shape

C:\Users\megan\AppData\Local\Temp\ipykernel_19864\1825955777.py:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  lineups = pd.read_csv("data/game_lineups.csv")

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,Christian Poulsen,substitutes,Defensive Midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,Niklas Moisander,starting_lineup,Centre-Back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,Maarten Martens,substitutes,Left Winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,Roy Beerens,starting_lineup,Right Winger,23,0

Dim: (2689973, 10)
- 103739 unique players
Relevant fields: date, game_id, player_id, type (starter/sub), position, team_captain (0/1)

Could be used to represent how many games a player has played in a season (started vs. subbed in), or if they are the team captain (these are typically talented, experienced players, so they probably earn more)

In [7]:
#Load and examine events data
events = pd.read_csv("data/game_events.csv")
events.head()

#Dimensions of the data
#events.shape

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77,Cards,610,Ajax Amsterdam,4425,"1. Yellow card , Mass confrontation",NaN,NaN
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77,Cards,383,PSV Eindhoven,33210,"1. Yellow card , Mass confrontation",NaN,NaN
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3,Goals,383,PSV Eindhoven,36500,", Header, 1. Tournament Goal Assist: , Corner,...",NaN,56416.0
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53,Goals,383,PSV Eindhoven,36500,", Right-footed shot, 2. Tournament Goal Assist...",NaN,146258.0
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74,Substitutions,383,PSV Eindhoven,36500,", Not reported",49499.0,NaN

Dim: (1102265, 11)
- 66973 unique players 

Relevant fields: player_id, type (card, goal, substitution)

Contains granular information about all of the events that happen in each game (date, game ID, minute, type of event, player involved, etc.)
- Might be useful, but may be easier to extract from a different data set

In [8]:
#Load and examine competitions data
competitions = pd.read_csv("data/competitions.csv")
competitions.head()

#Dimensions of the data
#competitions.shape

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,url,is_major_national_league
0,BE1,jupiler-pro-league,jupiler-pro-league,first_tier,domestic_league,19,Belgium,BE1,europa,https://www.transfermarkt.co.uk/jupiler-pro-le...,False
1,BESC,belgian-supercup,belgian-supercup,domestic_super_cup,other,19,Belgium,BE1,europa,https://www.transfermarkt.co.uk/belgian-superc...,False
2,CDR,copa-del-rey,copa-del-rey,domestic_cup,domestic_cup,157,Spain,ES1,europa,https://www.transfermarkt.co.uk/copa-del-rey/s...,False
3,CGB,efl-cup,efl-cup,league_cup,other,189,England,GB1,europa,https://www.transfermarkt.co.uk/efl-cup/starts...,False
4,CIT,italy-cup,italy-cup,domestic_cup,domestic_cup,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/italy-cup/star...,False

Dim: (44, 11)

Contains information about different competitions that players compete in (domestic league, cup, the country, federation, etc.)
- Similar domestic league info can be found in clubs data

In [ ]:
#Load and examine club data 
clubs = pd.read_csv("data/clubs.csv")
clubs.head()

#Dimensions of the data
clubs.shape

#Look at missing values
clubs.isna().sum()

Dim: (451, 17)

Relevant fields: name, domestic_competition_id, net_transfer_record

Could be used to map a player's club to the league that they compete in

net_transfer_record- might be interesting to see how much a club spends on transfers (are they getting good players or selling them?)

In [ ]:
#Load and examine club games data
club_games = pd.read_csv("data/club_games.csv")
club_games.head()

#Dimensions of the data
club_games.shape

#Look at missing values
club_games.isna().sum()

Dim: (156228, 11)
- 78114 unique games, 2926 unique clubs 

Relevant fields: game_id, club_id, own_goals, opponent_goals, is_win 

May or may not be used as it shows overall club performance as opposed to for an individual player
- Does a club's performance affect a player's market value?

In [ ]:
#Load and examine appearances data
appearances = pd.read_csv("data/appearances.csv")
appearances.head()

#Dimensions of the data
appearances.shape

#Look at missing values
appearances.isna().sum()

#Summary stats for numeric columns
appearances.describe()

Dim: (1731651, 13)
- 26601 unique players, 70251 unique games

Relevant fields: game_id, player_id, player_club_id, player_name, competition_id, yellow_cards, red_cards, goals, assists, minutes_played

Most stat columns (yellow/red cards, goals, assists) are right skewed
- Makes sense because these events are less common

minutes_played is actually left skewed
- Most professional athletes can play an entire game, so it's unlikely that players would have a low value for this metric
- Generally, players that get more minutes are better (with the exception of injury or other restrictions)